name: pet_pontual
description: Aplicativo Flutter de exemplo para gerenciar eventos de pets.
publish_to: "none"
homepage: https://github.com/augustofavaretto/pet_pontual
repository: https://github.com/augustofavaretto/pet_pontual
issue_tracker: https://github.com/augustofavaretto/pet_pontual/issues
documentation: https://github.com/augustofavaretto/pet_pontual/blob/main/README.md

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  provider: ^6.1.1
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.3.3
  path_provider: ^2.1.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  sqflite_common_ffi: ^2.3.3
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
